export const userConstants = {

    LIST_ALL_USERS_WEBSITE_REQUEST: 'LIST_ALL_USERS_WEBSITE_REQUEST',
    LIST_ALL_USERS_WEBSITE_SUCCESS: 'LIST_ALL_USERS_WEBSITE_SUCCESS',
    LIST_ALL_USERS_WEBSITE_FAILURE: 'LIST_ALL_USERS_WEBSITE_FAILURE'

};